/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BOverlay: typeof import('bootstrap-vue-next/components/BOverlay')['BOverlay']
    FooterView: typeof import('./src/components/FooterView.vue')['default']
    HeaderView: typeof import('./src/components/HeaderView.vue')['default']
    IBiPieChartFill: typeof import('~icons/bi/pie-chart-fill')['default']
    MainView: typeof import('./src/components/MainView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarView: typeof import('./src/components/SidebarView.vue')['default']
  }
  export interface GlobalDirectives {
    vBModal: typeof import('bootstrap-vue-next/directives/BModal')['vBModal']
  }
}
